[package]
name = "enscribe"
description = "setting ens names for smart contracts"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
eyre.workspace = true

foundry-cli.workspace = true
foundry-common.workspace = true
foundry-config.workspace = true

alloy-ens = { workspace = true, features = ["provider"] }
alloy-chains = { git = "https://github.com/alloy-rs/chains", rev = "45c5269bc8b937b2c79fca82fd5eb2aca8613b35"}
alloy-contract.workspace = true
alloy-provider = { workspace = true, features = ["reqwest", "ws", "ipc"] }
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
names = { version = "0.14.0", default-features = false }

[dev-dependencies]
tokio.workspace = true